site_name: SkeletonPHP
repo_url: https://github.com/nestorPons/skeletonPHP.git
site_description: "Framework modular."
site_author: NÃ©stor Pons
nav:
  - Inicio: 'index.md'
  - Estructura: 'estructura.md'
theme:
    name: readthedocs
    logo:
      icon: img/fish-skeleton-hand-drawn-bones.png
      favicon: img/fish-skeleton-hand-drawn-bones.png
      language: es
#    palette:
#        primary: teal
#        accent: orange
extra:
  social:
    - type: 'github'
      link: 'https://github.com/nestorPons'
markdown_extensions:
  - codehilite
  - admonition
